slice_name: Supermarket_LineChart
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: purchase_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 8
  datasource: 22__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby:
  - store_location
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: sales_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 748
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 69be4bd1-4d22-4e83-b8b8-9549553ff4a5
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(sales_amount)
    optionName: metric_q9uwdy0mwp_r2qx2okqg1
    sqlExpression: null
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  showTooltipTotal: true
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1M
  time_shift_color: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis: purchase_date
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 30
  y_axis_title_position: Left
query_context: '{"datasource": {"id": 22, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "purchase_date", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"time_grain_sqla": "P1M", "having": "", "where": ""}, "applied_time_extras":
  {}, "columns": [{"timeGrain": "P1M", "columnType": "BASE_AXIS", "sqlExpression":
  "purchase_date", "label": "purchase_date", "expressionType": "SQL"}, "store_location"],
  "metrics": [{"expressionType": "SIMPLE", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "sales_amount",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  748, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "69be4bd1-4d22-4e83-b8b8-9549553ff4a5", "verbose_name":
  null, "warning_markdown": null}, "aggregate": "SUM", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "SUM(sales_amount)", "optionName": "metric_q9uwdy0mwp_r2qx2okqg1"}],
  "orderby": [[{"expressionType": "SIMPLE", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "sales_amount",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  748, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "69be4bd1-4d22-4e83-b8b8-9549553ff4a5", "verbose_name":
  null, "warning_markdown": null}, "aggregate": "SUM", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "SUM(sales_amount)", "optionName": "metric_q9uwdy0mwp_r2qx2okqg1"},
  false]], "annotation_layers": [], "row_limit": 10000, "series_columns": ["store_location"],
  "series_limit": 0, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "time_offsets": [], "post_processing": [{"operation": "pivot", "options": {"index":
  ["purchase_date"], "columns": ["store_location"], "aggregates": {"SUM(sales_amount)":
  {"operator": "mean"}}, "drop_missing_columns": false}}, {"operation": "rename",
  "options": {"columns": {"SUM(sales_amount)": null}, "level": 0, "inplace": true}},
  {"operation": "flatten"}]}], "form_data": {"datasource": "22__table", "viz_type":
  "echarts_timeseries_line", "x_axis": "purchase_date", "time_grain_sqla": "P1M",
  "x_axis_sort_asc": true, "x_axis_sort_series": "name", "x_axis_sort_series_ascending":
  true, "metrics": [{"expressionType": "SIMPLE", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "sales_amount",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  748, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "69be4bd1-4d22-4e83-b8b8-9549553ff4a5", "verbose_name":
  null, "warning_markdown": null}, "aggregate": "SUM", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "SUM(sales_amount)", "optionName": "metric_q9uwdy0mwp_r2qx2okqg1"}],
  "groupby": ["store_location"], "adhoc_filters": [{"clause": "WHERE", "subject":
  "purchase_date", "operator": "TEMPORAL_RANGE", "comparator": "No filter", "expressionType":
  "SIMPLE"}], "order_desc": true, "row_limit": 10000, "truncate_metric": true, "show_empty_columns":
  true, "comparison_type": "values", "annotation_layers": [], "forecastPeriods": 10,
  "forecastInterval": 0.8, "x_axis_title_margin": 15, "y_axis_title_margin": 30, "y_axis_title_position":
  "Left", "sort_series_type": "sum", "color_scheme": "supersetColors", "time_shift_color":
  true, "seriesType": "line", "only_total": true, "opacity": 0.2, "markerSize": 6,
  "show_legend": true, "legendType": "scroll", "legendOrientation": "top", "x_axis_time_format":
  "smart_date", "rich_tooltip": true, "showTooltipTotal": true, "tooltipTimeFormat":
  "smart_date", "y_axis_format": "SMART_NUMBER", "truncateXAxis": true, "y_axis_bounds":
  [null, null], "extra_form_data": {}, "dashboards": [8], "force": false, "result_format":
  "json", "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 245c8bdf-0289-4b22-b825-1faa4d19b47a
version: 1.0.0
dataset_uuid: 97c2a39b-0ae0-4ab0-90eb-063a23d653bb
