name: Deploy Preset Assets to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRESET_API_TOKEN: ${{ secrets.PRESET_API_TOKEN }}
      PRESET_API_SECRET: ${{ secrets.PRESET_API_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Preset CLI
        run: pip install preset-cli

      - name: Sync Assets to Preset (Production)
        run: |
          preset-cli \
            --api-token $PRESET_API_TOKEN \
            --api-secret $PRESET_API_SECRET \
            --workspaces=https://303c4778.eu5a.app.preset.io/ \
            superset sync native . \
            --overwrite \
            --disallow-edits
